spring:
  # 메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER}
    password: ${EMAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true