spring:
  application:
    name: pillme

  config:
    import:
      - classpath:application-auth.yml
      - classpath:application-mail.yml
      - classpath:application-redis.yml
      - classpath:application-mysql.yml
      - optional:file:.env[.properties]