spring:
  application:
    name: pillme
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  config:
    import:
      - classpath:application-auth.yml
      - classpath:application-mail.yml
      - classpath:application-redis.yml
      - classpath:application-mysql.yml
      - classpath:application-firebase.yml
      - classpath:application-mongo.yml
#      - classpath:application-elastic.yml
      - optional:file:.env[.properties]

request-url: ${REQUEST_URL}
