spring:
  application:
    name: pillme

  messages:
    basename: messages, errors

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # 메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER}
    password: ${EMAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


  config:
    import:
      - classpath:application-h2.yml

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_VALIDITY}
  temporary-token-validity: ${JWT_TEMPORARY_VALIDITY}

# OAuth2 설정
oauth2:
  base-uri: ${BASE_URI}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI}

# SMS 설정
coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  sender-number: ${COOLSMS_SENDER_NUMBER}
  sms-type: ${COOLSMS_SMS_TYPE}
  country-code: ${COOLSMS_COUNTRY_CODE}

# 프론트엔드 URL
frontend:
  url: ${FRONTEND_URL}