spring:
  application:
    name: pillme
  messages:
    basename: messages, errors
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  config:
    import:
      - classpath:application-h2.yml